### ISSUE TITLE
spawn ENOENT

### ISSUE THREAD

**Issue by gregv21v** [jrudio/meteor-electron#21]
Whenever I run the app, I get this error.

=> Exited with code: 8
W20160320-12:45:49.281(-4)? (STDERR)
W20160320-12:45:49.282(-4)? (STDERR) events.js:72
W20160320-12:45:49.283(-4)? (STDERR)         throw er; // Unhandled 'error' event
W20160320-12:45:49.284(-4)? (STDERR)               ^
W20160320-12:45:49.284(-4)? (STDERR) Error: spawn ENOENT
W20160320-12:45:49.284(-4)? (STDERR)     at errnoException (child_process.js:1011:11)
W20160320-12:45:49.285(-4)? (STDERR)     at Process.ChildProcess._handle.onexit (child_process.js:802:34)

I don't know what I am doing wrong. I just installed jrudio:electron, then ran the meteor command in my project directory. The application runs fine before I install electron.

**Comment by jrudio** [comment]
It's definitely nothing wrong on your end. I forgot to handle the stderr on the spawned electron process.

Once I did handle the error, `electron-prebuilt` kept outputting a `localUrl is deprecated` error. So I'll fix that and push out an update in a little bit.

**Comment by jrudio** [comment]
Just pushed the update.

Make sure to remove the file: `.electron/app/main.js` and restart meteor so you don't get a deprecation error.

**Comment by jayitinc** [comment]
I'm getting the same error and I JUST added it using `meteor add jrudio:electron`

**Comment by jrudio** [comment]
@jayitinc Are you're getting an "Unhandled 'error' event" ?

**Comment by jayitinc** [comment]
@jrudio I'm getting the `Error: spawn ENOENT` error

**Comment by jayitinc** [comment]
@jrudio and yes I have `jrudio:electron 0.1.1`

**Comment by gregv21v** [comment]
I'm still getting the error too. I have version 1.2.1 of meteor if that helps.

**Comment by gregv21v** [comment]
I'm not sure if [this](http://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js) will help.

**Comment by gregv21v** [comment]
I figured out a solution. 
Replace Npm.require('child_process').spawn with Npm.require('cross-spawn'), and add it as a dependency. It turns out windows has a problem with Npm.require('child_process').spawn. The stackoverflow link I commented goes into more details. I made a poll request for the changes.

**Comment by jrudio** [comment]
:sob: Windows, man. 

Thanks for the pull request and for solving the issue!

**Comment by gregv21v** [comment]
I think there is something wrong with what is getting uploaded to the package server, because I can install the package manually, but when I install it via meteor add it doesn't work.

**Comment by jrudio** [comment]
I did get a message while publishing the package something along the lines
of " this package contains binary code, publish for each platform". So
meteor does... something to the package. Which is odd since using repo
directly just works (as you have said).

I did `meteor publish-for-arch jrudio:electron` on all of their build
machines, but maybe that's not enough. For Windows, it was a 32-bit arch,
so maybe a 64-bit version needs to be published?

**Comment by gregv21v** [comment]
That might work. I am using a 64-bit system.

There error is slightly different:

=> Exited with code: 8
   Building the application                  /                                       Buildin           B     B      B          BuildW20160321-22:18:03.389(-4)? (STDERR) jrudio_electron error:
W20160321-22:18:03.410(-4)? (STDERR)
W20160321-22:18:03.411(-4)? (STDERR) events.js:72
W20160321-22:18:03.411(-4)? (STDERR)         throw er; // Unhandled 'error' event
W20160321-22:18:03.411(-4)? (STDERR)               ^
W20160321-22:18:03.412(-4)? (STDERR) Error: spawn C:\Windows\TEMP\package-source2jo03e\jrudio_electron\.npm\package\node_modules\electron-prebuilt\dist\electron.exe ENOENT
W20160321-22:18:03.412(-4)? (STDERR)     at notFoundError (C:\Users\Gregory Venezia\AppData\Local\.meteor\packages\jrudio_electron\0.1.2\npm\node_modules\cross-spawn\node_modules\cross-spawn-async\lib\enoent.js:8:11)
W20160321-22:18:03.413(-4)? (STDERR)     at verifyENOENT (C:\Users\Gregory Venezia\AppData\Local\.meteor\packages\jrudio_electron\0.1.2\npm\node_modules\cross-spawn\node_modules\cross-spawn-async\lib\enoent.js:43:16)
W20160321-22:18:03.414(-4)? (STDERR)     at ChildProcess.cp.emit (C:\Users\Gregory Venezia\AppData\Local\.meteor\packages\jrudio_electron\0.1.2\npm\node_modules\cross-spawn\node_modules\cross-spawn-async\lib\enoent.js:30:19)
W20160321-22:18:03.414(-4)? (STDERR)     at Process.ChildProcess._handle.onexit (child_process.js:820:12)

**Comment by jrudio** [comment]
Yep, just tested on windows 64-bit and getting the same error. About to publish-for-arch and hopefully that resolves this issue.

**Comment by jayitinc** [comment]
Still not working on my end even running 0.1.3

**Comment by jrudio** [comment]
Welp, ran into another error while trying to publish for windows 64 bit. 

`error: Cannot override existing build`

And searching through [meteor's issue for any answers to this](https://github.com/meteor/meteor/issues/4477) shows that it has to do with a dependency that the npm packages require.

**Comment by jrudio** [comment]
@jayitinc You're on windows 64-bit, correct? 

0.1.3 was to see if maybe the windows 32 bit version didn't allow the build of 64 bit version. Which isn't necessary because it still builds as x86_32. 

But it seems the error that's causing the windows error is that when `electron-prebuilt` installs for first time it writes the path of electron to a file called `path.txt`. The location being written points to a temporary path, (I'm guessing meteor downloads the npm packages there and then moves the package to meteor's package path) and doesn't update to the new path.

Will see what options there are to fix this tomorrow.

**Comment by jayitinc** [comment]
@jrudio Yes I am running Windows 64-bit

**Comment by jrudio** [comment]
@jayitinc Thanks just wanted to make sure it was a windows only thing

**Comment by cluxter** [comment]
I was able to add the package under Windows 7, 64 bits. It was successfully downloaded and installed. However, here is what I get when I run "meteor":

```
E:\VIRTSHARE\testmeteor>meteor
[[[[[ ~\E\VIRTSHARE\testmeteor ]]]]]

=> Started proxy.
=> Started MongoDB.
W20160325-11:57:51.689(1)? (STDERR) jrudio_electron error:
=> Exited with code: 8
W20160325-11:57:51.807(1)? (STDERR)
W20160325-11:57:51.807(1)? (STDERR) events.js:72
W20160325-11:57:51.807(1)? (STDERR)         throw er; // Unhandled 'error' event
W20160325-11:57:51.808(1)? (STDERR)               ^
W20160325-11:57:51.808(1)? (STDERR) Error: spawn C:\Users\Justin\AppData\Local\Temp\package-sourcevzxdew
W20160325-11:57:51.808(1)? (STDERR)     at notFoundError (C:\Users\MGTB8955\AppData\Local\.meteor\packag
js:8:11)
W20160325-11:57:51.808(1)? (STDERR)     at verifyENOENT (C:\Users\MGTB8955\AppData\Local\.meteor\package
s:43:16)
W20160325-11:57:51.808(1)? (STDERR)     at ChildProcess.cp.emit (C:\Users\MGTB8955\AppData\Local\.meteor
enoent.js:30:19)
W20160325-11:57:51.808(1)? (STDERR)     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
```

Why does it try to do something in "C:\Users\Justin"?? I have absolutely no folder and no user named Justin.



So I tried to use this package under Linux (Archlinux), 64 bits. Meteor was not able to download the package. Here is what I got:

```
[cluxter@portable-b test]$ meteor add jrudio:electron
 => Errors while adding packages:

While checking for jrudio:electron@0.1.3:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

**Comment by jrudio** [comment]
The electron-prebuilt module has a post install script that downloads
electron  and writes the path of electron to a path.txt file. So when a dev
includes the module into their project it points to that path.

Well meteor requires package authors to build the package for all platforms
when binary code is involved. I guess when I build the package, Meteor runs
that post install script and ships it off to atmosphere with the path.txt
still pointing to my directory where I have electron installed.

Also, it's not working on Linux because I only published for windows. If
you download 0.1.2 (?), or one below the current version, then Linux should
be there. But the problem might still be there.

**Comment by tenshis** [comment]
I also receive the Justin path error:

```
W20160523-17:10:44.964(2)? (STDERR) Error: spawn C:\Users\Justin\AppData\Local\Temp\package-sourcevzxdew\jrudio_electron\.npm\package\node_modules\ele
ctron-prebuilt\dist\electron.exe ENOENT
```
